// <auto-generated>
using System.Reflection;

namespace FxResources.Microsoft.Extensions.Logging.Generators
{
    internal static class SR { }
}
namespace System
{
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.Microsoft.Extensions.Logging.Generators.SR)));

        /// <summary>Logging method names cannot start with _</summary>
        internal static string @InvalidLoggingMethodNameMessage => GetResourceString("InvalidLoggingMethodNameMessage", @"Logging method names cannot start with _");
        /// <summary>Logging method parameter names cannot start with _</summary>
        internal static string @InvalidLoggingMethodParameterNameMessage => GetResourceString("InvalidLoggingMethodParameterNameMessage", @"Logging method parameter names cannot start with _");
        /// <summary>Could not find a required type definition</summary>
        internal static string @MissingRequiredTypeTitle => GetResourceString("MissingRequiredTypeTitle", @"Could not find a required type definition");
        /// <summary>Could not find definition for type {0}</summary>
        internal static string @MissingRequiredTypeMessage => GetResourceString("MissingRequiredTypeMessage", @"Could not find definition for type {0}");
        /// <summary>Multiple logging methods cannot use the same event id within a class</summary>
        internal static string @ShouldntReuseEventIdsTitle => GetResourceString("ShouldntReuseEventIdsTitle", @"Multiple logging methods cannot use the same event id within a class");
        /// <summary>Multiple logging methods are using event id {0} in class {1}</summary>
        internal static string @ShouldntReuseEventIdsMessage => GetResourceString("ShouldntReuseEventIdsMessage", @"Multiple logging methods are using event id {0} in class {1}");
        /// <summary>Logging methods must return void</summary>
        internal static string @LoggingMethodMustReturnVoidMessage => GetResourceString("LoggingMethodMustReturnVoidMessage", @"Logging methods must return void");
        /// <summary>One of the arguments to a static logging method must implement the Microsoft.Extensions.Logging.ILogger interface</summary>
        internal static string @MissingLoggerArgumentTitle => GetResourceString("MissingLoggerArgumentTitle", @"One of the arguments to a static logging method must implement the Microsoft.Extensions.Logging.ILogger interface");
        /// <summary>One of the arguments to the static logging method '{0}' must implement the Microsoft.Extensions.Logging.ILogger interface</summary>
        internal static string @MissingLoggerArgumentMessage => GetResourceString("MissingLoggerArgumentMessage", @"One of the arguments to the static logging method '{0}' must implement the Microsoft.Extensions.Logging.ILogger interface");
        /// <summary>Logging methods must be static</summary>
        internal static string @LoggingMethodShouldBeStaticMessage => GetResourceString("LoggingMethodShouldBeStaticMessage", @"Logging methods must be static");
        /// <summary>Logging methods must be partial</summary>
        internal static string @LoggingMethodMustBePartialMessage => GetResourceString("LoggingMethodMustBePartialMessage", @"Logging methods must be partial");
        /// <summary>Logging methods cannot be generic</summary>
        internal static string @LoggingMethodIsGenericMessage => GetResourceString("LoggingMethodIsGenericMessage", @"Logging methods cannot be generic");
        /// <summary>Don't include a template for {0} in the logging message since it is implicitly taken care of</summary>
        internal static string @ShouldntMentionInTemplateMessage => GetResourceString("ShouldntMentionInTemplateMessage", @"Don't include a template for {0} in the logging message since it is implicitly taken care of");
        /// <summary>Don't include exception parameters as templates in the logging message</summary>
        internal static string @ShouldntMentionExceptionInMessageTitle => GetResourceString("ShouldntMentionExceptionInMessageTitle", @"Don't include exception parameters as templates in the logging message");
        /// <summary>Remove redundant qualifier (Info:, Warning:, Error:, etc) from the logging message since it is implicit in the specified log level.</summary>
        internal static string @RedundantQualifierInMessageMessage => GetResourceString("RedundantQualifierInMessageMessage", @"Remove redundant qualifier (Info:, Warning:, Error:, etc) from the logging message since it is implicit in the specified log level.");
        /// <summary>Redundant qualifier in logging message</summary>
        internal static string @RedundantQualifierInMessageTitle => GetResourceString("RedundantQualifierInMessageTitle", @"Redundant qualifier in logging message");
        /// <summary>Argument '{0}' is not referenced from the logging message</summary>
        internal static string @ArgumentHasNoCorrespondingTemplateMessage => GetResourceString("ArgumentHasNoCorrespondingTemplateMessage", @"Argument '{0}' is not referenced from the logging message");
        /// <summary>Argument is not referenced from the logging message</summary>
        internal static string @ArgumentHasNoCorrespondingTemplateTitle => GetResourceString("ArgumentHasNoCorrespondingTemplateTitle", @"Argument is not referenced from the logging message");
        /// <summary>Template '{0}' is not provided as argument to the logging method</summary>
        internal static string @TemplateHasNoCorrespondingArgumentMessage => GetResourceString("TemplateHasNoCorrespondingArgumentMessage", @"Template '{0}' is not provided as argument to the logging method");
        /// <summary>Logging template has no corresponding method argument</summary>
        internal static string @TemplateHasNoCorrespondingArgumentTitle => GetResourceString("TemplateHasNoCorrespondingArgumentTitle", @"Logging template has no corresponding method argument");
        /// <summary>Logging methods cannot have a body</summary>
        internal static string @LoggingMethodHasBodyMessage => GetResourceString("LoggingMethodHasBodyMessage", @"Logging methods cannot have a body");
        /// <summary>A LogLevel value must be supplied in the LoggerMessage attribute or as a parameter to the logging method</summary>
        internal static string @MissingLogLevelMessage => GetResourceString("MissingLogLevelMessage", @"A LogLevel value must be supplied in the LoggerMessage attribute or as a parameter to the logging method");
        /// <summary>Don't include log level parameters as templates in the logging message</summary>
        internal static string @ShouldntMentionLogLevelInMessageTitle => GetResourceString("ShouldntMentionLogLevelInMessageTitle", @"Don't include log level parameters as templates in the logging message");
        /// <summary>Don't include logger parameters as templates in the logging message</summary>
        internal static string @ShouldntMentionLoggerInMessageTitle => GetResourceString("ShouldntMentionLoggerInMessageTitle", @"Don't include logger parameters as templates in the logging message");
        /// <summary>Couldn't find a field of type Microsoft.Extensions.Logging.ILogger in class {0}</summary>
        internal static string @MissingLoggerFieldMessage => GetResourceString("MissingLoggerFieldMessage", @"Couldn't find a field of type Microsoft.Extensions.Logging.ILogger in class {0}");
        /// <summary>Couldn't find a field of type Microsoft.Extensions.Logging.ILogger</summary>
        internal static string @MissingLoggerFieldTitle => GetResourceString("MissingLoggerFieldTitle", @"Couldn't find a field of type Microsoft.Extensions.Logging.ILogger");
        /// <summary>Found multiple fields of type Microsoft.Extensions.Logging.ILogger in class {0}</summary>
        internal static string @MultipleLoggerFieldsMessage => GetResourceString("MultipleLoggerFieldsMessage", @"Found multiple fields of type Microsoft.Extensions.Logging.ILogger in class {0}");
        /// <summary>Found multiple fields of type Microsoft.Extensions.Logging.ILogger</summary>
        internal static string @MultipleLoggerFieldsTitle => GetResourceString("MultipleLoggerFieldsTitle", @"Found multiple fields of type Microsoft.Extensions.Logging.ILogger");
        /// <summary>Can't have the same template with different casing</summary>
        internal static string @InconsistentTemplateCasingMessage => GetResourceString("InconsistentTemplateCasingMessage", @"Can't have the same template with different casing");
        /// <summary>Can't have malformed format strings (like dangling {, etc)</summary>
        internal static string @MalformedFormatStringsMessage => GetResourceString("MalformedFormatStringsMessage", @"Can't have malformed format strings (like dangling {, etc)");
        /// <summary>Generating more than 6 arguments is not supported</summary>
        internal static string @GeneratingForMax6ArgumentsMessage => GetResourceString("GeneratingForMax6ArgumentsMessage", @"Generating more than 6 arguments is not supported");

    }
}

