using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CodeGen.PartialConstructor;

[Generator]
public class PartialConstructor : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // Register a syntax receiver to find struct declarations and constructor usages
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // The SyntaxReceiver will have collected potential diagnostics
        if (context.SyntaxReceiver is not SyntaxReceiver receiver) return;

        var source = new StringBuilder("""
                                       // <auto-generated/>
                                       """);

        source.AppendLine();
        foreach (var group in receiver.PartialConstructors.GroupBy(c => c.Ancestors().OfType<ClassDeclarationSyntax>().First().Identifier.ToString()))
        {
            var className = group.Key;
            var @namespace = group.First().Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
            if (@namespace != null)
            {
                source.AppendLine($"namespace {@namespace.Name}");
                source.AppendLine("{");
                source.AppendLine($"public partial class {className}");
                source.AppendLine("{");
                source.AppendLine($"    public {className}()");
                source.AppendLine("    {");
                foreach (var constructor in group)
                {
                    source.AppendLine($"        {constructor.Identifier}();");
                }
                source.AppendLine("    }");
                source.AppendLine("}");
                source.AppendLine("}");
            }
        }

        context.AddSource("PartialConstructor.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    class SyntaxReceiver : ISyntaxReceiver
    {
        public List<MethodDeclarationSyntax> PartialConstructors { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is MethodDeclarationSyntax method &&
                method.AttributeLists.SelectMany(attributes => attributes.Attributes)
                    .Any(attribute => attribute.Name.ToString() == "PartialConstructor")
               )
            {
                PartialConstructors.Add(method);
            }
        }
    }
}
